#!/usr/bin/env bash
# nginx server listen on port 80
sudo apt update
sudo apt install nginx -y

# Ensure Nginx is running
sudo service start nginx
sudo service enable nginx
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
