#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443 and 80.
apt update
apt install -y ufw
ufw default deny incoming
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw enable
